### PR TITLE
Manual sync with mlx90640 upstream

### PR DESCRIPTION
**Pull request by Gadgetoid**
Code changes manually copied across from upstream using dos2unix and a diff tool.

Includes commits from:
https://github.com/melexis/mlx90640-library/commit/b1a2ce472a283879c532ceab54560f1a4813c88c
to:
https://github.com/melexis/mlx90640-library/commit/5c1db3cbffefa6dbf9cd583e9dbeda47823b6c87

### CODE REVIEW

**Review by bakkerd — APPROVED** [review]
Checked out this branch and used it in my application, no issues.
Read through the diff, seems fine.

**Comment by Gadgetoid** [comment]
Thank you, I bet this is horribly out of date now though. :cry:

**Comment by bakkerd** [comment]
It is, but it still merges without conflicts. And anything closer to the current mlx library is good right?
Also yesterday I merged the latest mlx library into this branch, and they removed and added several API functions, so It will be quite a bit of work to validate that one.

**Comment by Gadgetoid** [comment]
> And anything closer to the current mlx library is good right?

Agreed!

> and they removed and added several API functions, so It will be quite a bit of work to validate that one.

:grimacing: 

Doesn't help that I found out the hard way how static sensitive the MLX90640 sensors are. Several of them simultaneously in fact. I've ordered a couple more for testing.

**Comment by LBuydens** [comment]
Hi Gadgetoid,
Could you comment on the static sensitivity of the MLX90640?  What occurred?  
We qualified the 90640 against the industry standard ESD HBM requirements.

**Pull request merged**
